// Centralized mapping of official grievance portals
// This acts as the single source of truth for portal URLs.
// The AI only returns a portalKey, and we resolve the URL here to avoid hallucinations.

export const portalDirectory = {
    "CPGRAMS": "https://pgportal.gov.in",
    "SWACHHATA": "https://swachhbharat.mygov.in",
    "BBMP_SAHAYA": "https://apps.bbmpgov.in/sahaya/",
    "MAHARASHTRA_GRIEVANCE": "https://grievances.maharashtra.gov.in",
    "DELHI_GRIEVANCE": "https://pgms.delhi.gov.in",
    "UP_IGRS": "https://jansunwai.up.nic.in",
    "CM_HELPLINE_MP": "https://cmhelpline.mp.gov.in",
    "TNGIS_TN": "https://gdp.tn.gov.in",
};

/**
 * Resolves a portal key to its official URL.
 * @param {string} portalKey - The key generated by the AI (e.g. 'CPGRAMS')
 * @returns {string|null} - The official URL or null if not found
 */
export const getPortalUrl = (portalKey) => {
    if (!portalKey) return null;
    // Normalize key to uppercase for consistent matching
    const normalizedKey = portalKey.toUpperCase().trim();
    return portalDirectory[normalizedKey] || null;
};
